### ISSUE TITLE
Example code to use BERTweet with only Transformers?

### ISSUE THREAD

**Issue by mralexisw** [VinAIResearch/BERTweet#12]
It is a bit onerous to mix APIs from `transformers` and `fairseq`. Any chance to have some demo code with `transformers` only?

**Comment by mcdavid109** [comment]
it is gonna be released soon. Please stay tuned :)

**Comment by datquocnguyen** [comment]
I am waiting for tranformers' developers to merge my pull request. In the meantime, you can use the BERTweet from this folk: https://github.com/datquocnguyen/transformers 
Example is available at: https://github.com/datquocnguyen/transformers/tree/master/model_cards/vinai/bertweet-base 
   
    bertweet = BertweetModel.from_pretrained("vinai/bertweet-base")
    tokenizer = BertweetTokenizer.from_pretrained("vinai/bertweet-base")

**Comment by dongxiangjue** [comment]
Did you try your example on the classification tasks, like SST-2? Because I encountered problems when I modified the run_glue.py file based on your example and run it. It generated "input_ids=[0, 64, 14, 169, 1340, 50044, 13, 135, 129, 15464, 4962, 2, [563, 732, 11, 614, 241], [563, 732, 11, 614, 241], [563, 732, 11, 614, 241], [563, 732, 11, 614, 241], [563, 732, 11, 614, 241],...]". I was wondering whether you know how to fix this issue. Thank you.
